tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=coverage.clover
                coverage:
                    file: coverage.clover
                    format: php-clover